### PR TITLE
Initial gradle setup

### PR DESCRIPTION
**Pull request by aalmiray**

### CODE REVIEW

**Comment by edvin** [comment]
Fantastic, thank you so much @aalmiray :) I'll start to play with this the coming weekend :)

**Comment by aalmiray** [comment]
Don't forget to update the personal data found in `gradle.properties` and `publishing.gradle`:smile:

**Comment by edvin** [comment]
I will :) Looking forward to playing with this. Man, the Gradle API's are a lot slicker than the Maven counterparts :)

**Comment by edvin** [comment]
Hey! I've worked a little on the plugin and tried to apply it to the fxldemo-gradle demo project. I haven't published it to jcenter yet, so I published it to my local maven repo instead. I'm a total gradle n00b, so I'm most probably doing something horribly wrong, but I can't seem to figure it out. Can you help me with a small template built script that uses the plugin? I tried this:

``` groovy
group 'no.tornado'
version '1.0'

apply plugin: 'java'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile 'org.controlsfx:controlsfx:8.40.10'
}

buildscript {
    repositories {
        mavenLocal()
    }
    dependencies {
        classpath 'no.tornado.fxlauncher:fxlauncher-gradle-plugin:1.0.11'
    }
}

apply plugin: no.tornado.fxlauncher.gradle.FXLauncherPlugin
```

I get this error:

```
Warning:<i><b>root project 'fxldemo-gradle': Unable to resolve additional project configuration.</b>
Details: groovy.lang.MissingPropertyException: No such property: id for class: org.gradle.api.internal.artifacts.DefaultResolvedArtifact
Possible solutions: file</i>
```

Sorry for bothering you with this :)

**Comment by aalmiray** [comment]
Did you try using a `String` instead of a full qualified class name?, i.e, 

```
apply plugin: 'no.tornado.fxlauncher.gradle.FXLauncherPlugin'
```

also, it's recommended to define plugins a the top of the script. I'd move the `buildscript` block to the top.

**Comment by edvin** [comment]
I put the `buildscript` block on the top and added single quotes to the plugin name, then I got:

`Error:(10, 0) Plugin with id 'no.tornado.fxlauncher.gradle.FXLauncherPlugin' not found.`

I've verified that the coordinates `no.tornado.fxlauncher:fxlauncher-gradle-plugin:1.0.11` are correct, the jar is in my local repo here:

`/Users/edvin/.m2/repository/no/tornado/fxlauncher/fxlauncher-gradle-plugin/1.0.11/fxlauncher-gradle-plugin-1.0.11.jar`

The plugin jar contains these files:

```
   creating: META-INF/
  inflating: META-INF/MANIFEST.MF    
   creating: no/
   creating: no/tornado/
   creating: no/tornado/fxlauncher/
   creating: no/tornado/fxlauncher/gradle/
  inflating: no/tornado/fxlauncher/gradle/CopyAppDependenciesTask$_copyDependencies_closure1$_closure2$_closure3.class  
  inflating: no/tornado/fxlauncher/gradle/CopyAppDependenciesTask$_copyDependencies_closure1$_closure2.class  
  inflating: no/tornado/fxlauncher/gradle/CopyAppDependenciesTask$_copyDependencies_closure1.class  
  inflating: no/tornado/fxlauncher/gradle/CopyAppDependenciesTask.class  
  inflating: no/tornado/fxlauncher/gradle/FXLauncherExtension.class  
  inflating: no/tornado/fxlauncher/gradle/FXLauncherPlugin$_apply_closure1.class  
  inflating: no/tornado/fxlauncher/gradle/FXLauncherPlugin$_apply_closure2$_closure3.class  
  inflating: no/tornado/fxlauncher/gradle/FXLauncherPlugin$_apply_closure2$_closure4.class  
  inflating: no/tornado/fxlauncher/gradle/FXLauncherPlugin$_apply_closure2.class  
  inflating: no/tornado/fxlauncher/gradle/FXLauncherPlugin.class  
  inflating: no/tornado/fxlauncher/gradle/GenerateApplicationManifestTask$_setupClassLoader_closure1.class  
  inflating: no/tornado/fxlauncher/gradle/GenerateApplicationManifestTask.class  
   creating: META-INF/gradle-plugins/
  inflating: META-INF/gradle-plugins/no.tornado.fxlauncher.properties  
```

That output got me thinking - `no.tornado.fxlauncher` seems to be the plugin id, right? So I used that instead and got:

`Error:(10, 0) Could not find property 'jar' on task set.`

That sounds better :) Maybe I'm missing something else now?

**Comment by edvin** [comment]
I put `apply plugin: 'java'` first, and now I get:

 `Warning:<i><b>root project 'fxldemo-gradle': Unable to resolve additional project configuration.</b>
Details: groovy.lang.MissingPropertyException: No such property: id for class: org.gradle.api.internal.artifacts.DefaultResolvedArtifact
Possible solutions: file</i>`

**Comment by edvin** [comment]
Even with the error, IDEA shows me some tasks for the fxlauncher plugin now:
- copyAppDependencies
- generateApplicationManifest

copyAppDependencies also seem to be working, so I think the error is somehow related to the refresh functionality in IDEA, so I'll ignore them for now and see how this goes. Thanks again for helping me :)

**Comment by edvin** [comment]
One last n00b question? How do you define the properties the plugin needs in the build script? For example `fxlauncher.applicationUrl`?

**Comment by edvin** [comment]
I think I figured it out:

```
fxlauncher {
    applicationUrl 'http://fxldemo.tornado.no/'
}
```

**Comment by aalmiray** [comment]
Yup, that's one way. The other is to use the `=` operator, such as

```
fxlauncher {
    applicationUrl = 'http://fxldemo.tornado.no/'
}
```

**Comment by edvin** [comment]
Great! When I'm done with the plugin I'll read the Gradle manual, just to be sure I did everything in exactly the opposite order any sane person would do this in.. hehe :)

**Comment by edvin** [comment]
I have some more questions for the two remaining tasks, but I totally understand if you don't have time :)

For the `EmbedApplicationManifest` step I need to get a hold of the fxlauncher.jar and copy it to the build/fxlauncher folder before I open it and add the manifest to it. I see in `FXLauncherPlugin.groovy` how I can get a hold of a `Dependency` that represents fxlauncher - is it possible to get to the actual jar (file ref) from there?

I have:

``` groovy
FXLauncherExtension extension = project.extensions.findByName('fxlauncher')
Dependency fxlauncher = project.dependencies.create('no.tornado:fxlauncher:' + extension.fxlauncherVersion)
```

I guess I don't need a `Dependency` but an `Artifact` or something that has a `File` reference, is that correct?

**Comment by edvin** [comment]
I got to it like this, but it is probably not the best way to do it:

``` groovy
Configuration config = project.configurations.getByName(FXLauncherPlugin.CONFIGURATION_NAME)
ResolvedArtifact fxlauncher = config.resolvedConfiguration.resolvedArtifacts.find { it.name == 'fxlauncher' }
```

Embed manifest is now working :)

**Pull request merged**
