### PR TITLE
Added the option to set name and title.

### PR DESCRIPTION
**Pull request by jochenschmich**
I want to be able to optionally set a name and title for the package.
This change should make it work.

### CODE REVIEW

**Comment by edvin** [comment]
Thanks :) Nice addition!

**Comment by jochenschmich** [comment]
Thanks for merging 👍 :-) ! Uhm, will you deploy a new version to Maven Central?

**Comment by edvin** [comment]
There is a snapshot available at oss.sonatype.org already,  and we'll release TornadoFX 1.7.15 with this fix within week most probably.

**Comment by jochenschmich** [comment]
OK - thank you!

**Pull request merged**
