### PR TITLE
Add stopOnUpdateErrors to manifest

### PR DESCRIPTION
**Pull request by gcstang**
Updated to add the stopOnUpdateErrors to the manifest

### CODE REVIEW

**Comment by edvin** [comment]
This is good, but we still need to change FXLauncher to accept this parameter and save it in the manifest. Will you give that a go as well? Should be pretty straight forward.

**Comment by gcstang** [comment]
By that name do you mean the FXLauncherPlugin in this project or the actual FXLauncher project?

**Comment by edvin** [comment]
The actual FXLauncher. Sending that command to FXLauncher now wouldn't result in it being added to the manifest.

**Comment by gcstang** [comment]
Ok, I'll take a look at that one.
Thank you

**Comment by edvin** [comment]
Perfect! Let me know if you get stuck on anything.

**Comment by gcstang** [comment]
I believe I got it all, tell me if I missed anything in that project.

**Pull request merged**
